// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrattonOakmontServices;

namespace StrattonOakmontServices.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211124173325_NewModelM")]
    partial class NewModelM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DateSecurity", b =>
                {
                    b.Property<int>("DateTimesChangesId")
                        .HasColumnType("int");

                    b.Property<int>("SecuritiesId")
                        .HasColumnType("int");

                    b.HasKey("DateTimesChangesId", "SecuritiesId");

                    b.HasIndex("SecuritiesId");

                    b.ToTable("DateSecurity");
                });

            modelBuilder.Entity("DateSecurityInd", b =>
                {
                    b.Property<int>("DateTimesChangesId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityIndId")
                        .HasColumnType("int");

                    b.HasKey("DateTimesChangesId", "SecurityIndId");

                    b.HasIndex("SecurityIndId");

                    b.ToTable("DateSecurityInd");
                });

            modelBuilder.Entity("DateSecuritySub", b =>
                {
                    b.Property<int>("DateTimesChangesId")
                        .HasColumnType("int");

                    b.Property<int>("SecuritySubsId")
                        .HasColumnType("int");

                    b.HasKey("DateTimesChangesId", "SecuritySubsId");

                    b.HasIndex("SecuritySubsId");

                    b.ToTable("DateSecuritySub");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StrattonOakmontModels.Abligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanySecId")
                        .HasColumnType("int");

                    b.Property<string>("FinalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecMainConId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("CompanySecId");

                    b.HasIndex("SecMainConId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Abligations");
                });

            modelBuilder.Entity("StrattonOakmontModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StrattonOakmontModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Сapitalization")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("StrattonOakmontModels.Date", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AbligationId")
                        .HasColumnType("int");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("DepositReceiptsId")
                        .HasColumnType("int");

                    b.Property<int?>("ForwardId")
                        .HasColumnType("int");

                    b.Property<int?>("FuturesId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<int?>("StonkId")
                        .HasColumnType("int");

                    b.Property<int?>("WrightId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbligationId");

                    b.HasIndex("BillId");

                    b.HasIndex("DepositReceiptsId");

                    b.HasIndex("ForwardId");

                    b.HasIndex("FuturesId");

                    b.HasIndex("OptionId");

                    b.HasIndex("StonkId");

                    b.HasIndex("WrightId");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("StrattonOakmontModels.Indastrial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Indastrials");
                });

            modelBuilder.Entity("StrattonOakmontModels.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanySecId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("CompanySecId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<string>("FinalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Getter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LifeCycle")
                        .HasColumnType("int");

                    b.Property<string>("PerSent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecSubConId")
                        .HasColumnType("int");

                    b.Property<string>("Setter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("SecSubConId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.DepositReceipts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AbligationId")
                        .HasColumnType("int");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<string>("FinalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LifeCycle")
                        .HasColumnType("int");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecSubConId")
                        .HasColumnType("int");

                    b.Property<int?>("StonkId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AbligationId");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("SecSubConId");

                    b.HasIndex("StonkId");

                    b.HasIndex("UserSecId");

                    b.ToTable("DepositReceipts");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Forward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int");

                    b.Property<string>("FinalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndastrialSecId")
                        .HasColumnType("int");

                    b.Property<string>("NameIndastry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecIndConId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("IndastrialSecId");

                    b.HasIndex("SecIndConId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Forwards");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Futures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int");

                    b.Property<string>("FinalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndastrialSecId")
                        .HasColumnType("int");

                    b.Property<string>("NameIndastry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecIndConId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("IndastrialSecId");

                    b.HasIndex("SecIndConId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Futures");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int");

                    b.Property<string>("FinalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndastrialSecId")
                        .HasColumnType("int");

                    b.Property<string>("NameIndastry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecIndConId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("IndastrialSecId");

                    b.HasIndex("SecIndConId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Relation.SecIndCon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("SecIndCons");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Relation.SecMainCon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("SecMainCons");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Relation.SecSubCon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("SecSubCons");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.SecurityInd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("UserSecId");

                    b.ToTable("SecurityInds");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Type.SecuritySub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int>("LifeCycle")
                        .HasColumnType("int");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("UserSecId");

                    b.ToTable("SecuritySubs");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Wright", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActiveId")
                        .HasColumnType("int");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int");

                    b.Property<string>("FinalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndastrialSecId")
                        .HasColumnType("int");

                    b.Property<string>("NameIndastry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecIndConId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveId");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("IndastrialSecId");

                    b.HasIndex("SecIndConId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Wrights");
                });

            modelBuilder.Entity("StrattonOakmontModels.Stonk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CategorySecId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanySecId")
                        .HasColumnType("int");

                    b.Property<bool>("Divisibility")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SecMainConId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorySecId");

                    b.HasIndex("CompanySecId");

                    b.HasIndex("SecMainConId");

                    b.HasIndex("UserSecId");

                    b.ToTable("Stonks");
                });

            modelBuilder.Entity("StrattonOakmontModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DateSecurity", b =>
                {
                    b.HasOne("StrattonOakmontModels.Date", null)
                        .WithMany()
                        .HasForeignKey("DateTimesChangesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrattonOakmontModels.Security", null)
                        .WithMany()
                        .HasForeignKey("SecuritiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DateSecurityInd", b =>
                {
                    b.HasOne("StrattonOakmontModels.Date", null)
                        .WithMany()
                        .HasForeignKey("DateTimesChangesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrattonOakmontModels.Securityes.SecurityInd", null)
                        .WithMany()
                        .HasForeignKey("SecurityIndId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DateSecuritySub", b =>
                {
                    b.HasOne("StrattonOakmontModels.Date", null)
                        .WithMany()
                        .HasForeignKey("DateTimesChangesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrattonOakmontModels.Securityes.Type.SecuritySub", null)
                        .WithMany()
                        .HasForeignKey("SecuritySubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StrattonOakmontModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StrattonOakmontModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrattonOakmontModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StrattonOakmontModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StrattonOakmontModels.Abligation", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Company", "CompanySec")
                        .WithMany()
                        .HasForeignKey("CompanySecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecMainCon", "SecMainCon")
                        .WithMany("Abligations")
                        .HasForeignKey("SecMainConId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("CompanySec");

                    b.Navigation("SecMainCon");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Date", b =>
                {
                    b.HasOne("StrattonOakmontModels.Abligation", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("AbligationId");

                    b.HasOne("StrattonOakmontModels.Securityes.Bill", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("BillId");

                    b.HasOne("StrattonOakmontModels.Securityes.DepositReceipts", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("DepositReceiptsId");

                    b.HasOne("StrattonOakmontModels.Securityes.Forward", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("ForwardId");

                    b.HasOne("StrattonOakmontModels.Securityes.Futures", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("FuturesId");

                    b.HasOne("StrattonOakmontModels.Securityes.Option", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("OptionId");

                    b.HasOne("StrattonOakmontModels.Stonk", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("StonkId");

                    b.HasOne("StrattonOakmontModels.Securityes.Wright", null)
                        .WithMany("DateTimesChanges")
                        .HasForeignKey("WrightId");
                });

            modelBuilder.Entity("StrattonOakmontModels.Security", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany("Securities")
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Company", "CompanySec")
                        .WithMany("Securities")
                        .HasForeignKey("CompanySecId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany("Securities")
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("CompanySec");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Bill", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecSubCon", "SecSubCon")
                        .WithMany("Bills")
                        .HasForeignKey("SecSubConId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("SecSubCon");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.DepositReceipts", b =>
                {
                    b.HasOne("StrattonOakmontModels.Abligation", "Abligation")
                        .WithMany()
                        .HasForeignKey("AbligationId");

                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecSubCon", "SecSubCon")
                        .WithMany("DepositReceipts")
                        .HasForeignKey("SecSubConId");

                    b.HasOne("StrattonOakmontModels.Stonk", "Stonk")
                        .WithMany()
                        .HasForeignKey("StonkId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("Abligation");

                    b.Navigation("CategorySec");

                    b.Navigation("SecSubCon");

                    b.Navigation("Stonk");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Forward", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Indastrial", "IndastrialSec")
                        .WithMany("Forwards")
                        .HasForeignKey("IndastrialSecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecIndCon", "SecIndCon")
                        .WithMany("Forwards")
                        .HasForeignKey("SecIndConId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("IndastrialSec");

                    b.Navigation("SecIndCon");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Futures", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Indastrial", "IndastrialSec")
                        .WithMany("Futures")
                        .HasForeignKey("IndastrialSecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecIndCon", "SecIndCon")
                        .WithMany("Futures")
                        .HasForeignKey("SecIndConId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("IndastrialSec");

                    b.Navigation("SecIndCon");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Option", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Indastrial", "IndastrialSec")
                        .WithMany("Options")
                        .HasForeignKey("IndastrialSecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecIndCon", "SecIndCon")
                        .WithMany("Options")
                        .HasForeignKey("SecIndConId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("IndastrialSec");

                    b.Navigation("SecIndCon");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.SecurityInd", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany("SecuritiesInd")
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Type.SecuritySub", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany("SecuritiesSub")
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Wright", b =>
                {
                    b.HasOne("StrattonOakmontModels.Security", "Active")
                        .WithMany()
                        .HasForeignKey("ActiveId");

                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Indastrial", "IndastrialSec")
                        .WithMany("Wrights")
                        .HasForeignKey("IndastrialSecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecIndCon", "SecIndCon")
                        .WithMany("Wrights")
                        .HasForeignKey("SecIndConId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("Active");

                    b.Navigation("CategorySec");

                    b.Navigation("IndastrialSec");

                    b.Navigation("SecIndCon");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Stonk", b =>
                {
                    b.HasOne("StrattonOakmontModels.Category", "CategorySec")
                        .WithMany()
                        .HasForeignKey("CategorySecId");

                    b.HasOne("StrattonOakmontModels.Company", "CompanySec")
                        .WithMany()
                        .HasForeignKey("CompanySecId");

                    b.HasOne("StrattonOakmontModels.Securityes.Relation.SecMainCon", "SecMainCon")
                        .WithMany("Stonks")
                        .HasForeignKey("SecMainConId");

                    b.HasOne("StrattonOakmontModels.User", "UserSec")
                        .WithMany()
                        .HasForeignKey("UserSecId");

                    b.Navigation("CategorySec");

                    b.Navigation("CompanySec");

                    b.Navigation("SecMainCon");

                    b.Navigation("UserSec");
                });

            modelBuilder.Entity("StrattonOakmontModels.Abligation", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.Category", b =>
                {
                    b.Navigation("Securities");

                    b.Navigation("SecuritiesInd");

                    b.Navigation("SecuritiesSub");
                });

            modelBuilder.Entity("StrattonOakmontModels.Company", b =>
                {
                    b.Navigation("Securities");
                });

            modelBuilder.Entity("StrattonOakmontModels.Indastrial", b =>
                {
                    b.Navigation("Forwards");

                    b.Navigation("Futures");

                    b.Navigation("Options");

                    b.Navigation("Wrights");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Bill", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.DepositReceipts", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Forward", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Futures", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Option", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Relation.SecIndCon", b =>
                {
                    b.Navigation("Forwards");

                    b.Navigation("Futures");

                    b.Navigation("Options");

                    b.Navigation("Wrights");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Relation.SecMainCon", b =>
                {
                    b.Navigation("Abligations");

                    b.Navigation("Stonks");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Relation.SecSubCon", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("DepositReceipts");
                });

            modelBuilder.Entity("StrattonOakmontModels.Securityes.Wright", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.Stonk", b =>
                {
                    b.Navigation("DateTimesChanges");
                });

            modelBuilder.Entity("StrattonOakmontModels.User", b =>
                {
                    b.Navigation("Securities");
                });
#pragma warning restore 612, 618
        }
    }
}
